### ISSUE TITLE
create-files fails

### ISSUE THREAD

**Issue by slloyd88** [madeyourday/SVG-Icon-Font-Generator#4]
php svg-icon-font-generator.phar create-files wasql_icons.svg /var/www/fonticons

PHP Warning:  require(phar:///var/www/SVG-Icon-Font-Generator/svg-icon-font-generator.phar/vendor/symfony/class-loader/Symfony/Component/ClassLoader/UniversalClassLoader.php): failed to open stream: phar error: "vendor/symfony/class-loader/Symfony/Component/ClassLoader/UniversalClassLoader.php" is not a file in phar "/var/www/SVG-Icon-Font-Generator/svg-icon-font-generator.phar" in phar:///var/www/SVG-Icon-Font-Generator/svg-icon-font-generator.phar/run.php on line 9
PHP Fatal error:  require(): Failed opening required 'phar:///var/www/SVG-Icon-Font-Generator/svg-icon-font-generator.phar/vendor/symfony/class-loader/Symfony/Component/ClassLoader/UniversalClassLoader.php' (include_path='phar:///var/www/SVG-Icon-Font-Generator/svg-icon-font-generator.phar:.:/usr/share/php:/usr/share/pear') in phar:///var/www/SVG-Icon-Font-Generator/svg-icon-font-generator.phar/run.php on line 9

**Comment by ausi** [comment]
The bug should be fixed now. Please try it again with the latest version.

**Comment by slloyd88** [comment]
Thanks ausi. That worked.
