### ISSUE TITLE
Compiling the RockSolid Icon Font is broken using SVG-Icon-Font-Generator

### ISSUE THREAD

**Issue by Donno191** [madeyourday/SVG-Icon-Font-Generator#7]
![broken](https://user-images.githubusercontent.com/10705947/67750769-894abd00-fa38-11e9-9fd7-44698b7bed48.png)

**Comment by Donno191** [comment]
using PHP 7.3.6

**Comment by ausi** [comment]
Did you convert the SVG font to TTF/WOFF files after using the icon font generator?
