### ISSUE TITLE
Says it is success but does not generate valid svg font

### ISSUE THREAD

**Issue by slloyd88** [madeyourday/SVG-Icon-Font-Generator#9]
The program says it created everything successfully but when I view the html file all the icons show up as just empty boxes.

Here is the output.

d:\SVG-Icon-Font-Generator>php svg-icon-font-generator.phar create-font d:\wasql_svg wasql_icons.svg --rename-files
reading files from "d:\wasql_svg" ...
PHP Notice:  A non well formed numeric value encountered in phar://D:/SVG-Icon-Font-Generator/svg-icon-font-generator.phar/src/MadeYourDay/SVG/Document.php on line 93
PHP Notice:  A non well formed numeric value encountered in phar://D:/SVG-Icon-Font-Generator/svg-icon-font-generator.phar/src/MadeYourDay/SVG/Document.php on line 96
PHP Notice:  A non well formed numeric value encountered in phar://D:/SVG-Icon-Font-Generator/svg-icon-font-generator.phar/src/MadeYourDay/SVG/Document.php on line 93
PHP Notice:  A non well formed numeric value encountered in phar://D:/SVG-Icon-Font-Generator/svg-icon-font-generator.phar/src/MadeYourDay/SVG/Document.php on line 96
writing font to "wasql_icons.svg" ...
created wasql_icons.svg successfully

d:\SVG-Icon-Font-Generator>php svg-icon-font-generator.phar create-info wasql_icons.svg wasql_icons.html
reading font file from "D:\SVG-Icon-Font-Generator\wasql_icons.svg" ...
writing HTML file to "wasql_icons.html" ...
created HTML info page successfully

d:\SVG-Icon-Font-Generator>php svg-icon-font-generator.phar create-css wasql_icons.svg wasql_icons.css
reading font file from "D:\SVG-Icon-Font-Generator\wasql_icons.svg" ...
writing CSS file to "wasql_icons.css" ...
created CSS file successfully

**Comment by ausi** [comment]
Are you using a [browser that supports SVG fonts](https://caniuse.com/#feat=svg-fonts) to view the HTML file?

If not, you need to convert the SVG font into the WOFF and WOFF2 format which is supported by most browsers.

**Comment by ausi** [comment]
@slloyd88 Any updates on this issue?

**Comment by slloyd88** [comment]
I am using the latest Chrome browser. Some icons show up but most do not.

![image](https://user-images.githubusercontent.com/9954232/82809583-aa964f00-9e49-11ea-95eb-5da617ad19b1.png)

**Comment by ausi** [comment]
Chrome does not support SVG fonts, you have to convert the fonts to woff first.

> Is there a command-line way to convert a svg font to woff and ttf?

I think FontForge has a command line tool that can be used for this conversion.
